export const artworkCategories = ["portraits", "animals", "still life"];

export const artworks = [
  {
    id: "portrait-01",
    title: "self portrait no. 1",
    category: "portraits",
    imageSrc: "https://picsum.photos/id/1027/900/1200",
    alt: "placeholder self portrait artwork",
    artistComment: "lorem ipsum dolor sit amet, this piece explores softness and silence.",
    year: "",
    medium: "digital painting",
    featured: true,
  },
  {
    id: "portrait-02",
    title: "quiet gaze",
    category: "portraits",
    imageSrc: "https://picsum.photos/id/1005/900/1200",
    alt: "placeholder portrait with warm lighting",
    artistComment: "lorem ipsum dolor sit amet, a study of pause and memory.",
    featured: false,
  },
  {
    id: "animal-01",
    title: "small moon cat",
    category: "animals",
    imageSrc: "https://picsum.photos/id/237/900/1200",
    alt: "placeholder cat portrait",
    artistComment: "lorem ipsum dolor sit amet, this one is playful and dreamy.",
    featured: true,
  },
  {
    id: "animal-02",
    title: "forest companion",
    category: "animals",
    imageSrc: "https://picsum.photos/id/433/900/1200",
    alt: "placeholder animal portrait in cool tones",
    artistComment: "lorem ipsum dolor sit amet, painted with gentle contrast.",
    featured: false,
  },
  {
    id: "still-01",
    title: "tea and late light",
    category: "still life",
    imageSrc: "https://picsum.photos/id/292/900/1200",
    alt: "placeholder still life composition",
    artistComment: "lorem ipsum dolor sit amet, a quiet table scene.",
    featured: true,
  },
  {
    id: "still-02",
    title: "letters and petals",
    category: "still life",
    imageSrc: "https://picsum.photos/id/1080/900/1200",
    alt: "placeholder still life with petals",
    artistComment: "lorem ipsum dolor sit amet, soft palettes with texture layers.",
    featured: false,
  },
];
